### ISSUE TITLE
Start all servers on port 8000

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/graphql-benchmarks#10]
Currently all servers start on different ports.

**.devcontainer/Dockerfile**
```dockerfile
EXPOSE 8080 8081 8082 8083 8084 3000
```

Ideally we would like to expose every service on a single port `8000`. While running the tests, we will start the service, run the benchmark and stop the service completely only after which move on to the next service.

**Comment by A-N-uraag** [comment]
Hi @tusharmath, can I work on this?

**Comment by b4s36t4** [comment]
I would like to work on this, @tusharmath Please assign to me :)
