### ISSUE TITLE
Add Hasura to the Benchmarks

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/graphql-benchmarks#261]
Add Hasura to the benchmarks to compare GraphQL performance

**Comment by tusharmath** [comment]
@Dhanus3133 Assigning it to @kabir276. Let's welcome him as our newest member!

**Comment by kabir276** [comment]
I won't be working on this issue @tusharmath

**Comment by tusharmath** [comment]
@Dhanus3133 Feel free to pick this issue, thanks.
