### ISSUE TITLE
run all the benchmarks in parallel

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/graphql-benchmarks#318]
Currently the benchmarks run in sequence one after the other. We want to change that so that all the benchmarks can run in parallel. For each server start with the "greet" query, moving on to a list of posts and then to posts with users.

**Technical Requirements**
- Ensure each GraphQL server runs independent of the other in a single runner.

**Comment by webbdays** [comment]
Running parallel in a single server/runner, doesn't it effect the metrics? I think so.

**Comment by daveads** [comment]
> Running parallel in a single server/runner, doesn't it effect the metrics? I think so.

lol Thanks, yea it does...

**Comment by daveads** [comment]
![Screenshot 2024-07-14 at 10-33-33 trying shit · daveads_graphql-benchmarks@c808970](https://github.com/user-attachments/assets/38e90959-aa57-4ffa-b217-9c03d4a2ec35)


@tusharmath  you might want to check this 

https://github.com/daveads/graphql-benchmarks/actions/runs/9922729321/job/27412217401
