### ISSUE TITLE
Rewrite GraphQL Implementation using netflix DGS using Kotlin/Java

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/graphql-benchmarks#34]
**Technical Requirements**
- Use latest version of all the libraries
- Use connection pooling for the http client
- Make sure localhost:3000 is used as a proxy for http client
- Implement the graphQL schema as explained here https://github.com/tailcallhq/graphql-benchmarks#graphql-schema
- Ensure not batching and caching is happening in the http client.

**Comment by ayewo** [comment]
Please assign me ✋ but before you do, can you please clarify the task? https://github.com/Netflix/dgs-framework is already written in Kotlin/Java/Spring Boot

**Comment by ayewo** [comment]
@tusharmath 
After multiple readings, it sounds like you want to modernize the dependencies and look for ways to speed up the latest version of Netflix DGS? Is my understanding correct?

**Comment by sakshambp** [comment]
Can you please mention the success criteria for this? I am interested in attempting the same

**Comment by tusharmath** [comment]
Updated the issue, let me know if it's understandable now. Overall we just need to re-write the graphql implementation using netflix DGS

**Comment by ayewo** [comment]
@tusharmath the code for the rewrite are these 5 .java files at [`graphql-benchmarks/graphql/netflix_dgs/`](https://github.com/tailcallhq/graphql-benchmarks/tree/main/graphql/netflix_dgs/src/main/java/com/example/netflixdgs), correct?

**Comment by ezhil56x** [comment]
Can I get this assigned? I hope I have completed most of the work. Next time I'll start working only I get assigned. Sorry for the confusion 🥲 @ayewo

**Comment by ayewo** [comment]
> @ezhil56x: The Tailcall Inc. team prefers to assign a single contributor to the issue rather than let anyone attempt it right away. We recommend waiting for a confirmation from a member before getting started.

@ezhil56x
As quoted above, the @algora-pbc bot already explained the rules to you but you somehow chose to ignore.

Assignment is based on a first-come first-served basis with some discretion applied by @tusharmath if you are a newcomer. If you stick around, there's plenty of work to go round so no need to blind side other contributors by trying to game the system.

**Comment by tusharmath** [comment]
@ayewo have you been able to make any progress on this issue or would you prefer it to be reassigned to someone else if you have too much on your plate already.

**Comment by ayewo** [comment]
@tusharmath I’ll open a PR today.

I wasn’t feeling well 2 days ago and was outdoors for most of yesterday which is why I wasn’t able to finish.
