### ISSUE TITLE
Run the benchmarks automatically on `benchmarking-runner`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/graphql-benchmarks#6]
**Technical Requirements**
- Run benchmarks for all PRs on `benchmarking-runner` runner.
- It should follow the steps we have documented and automatically generate
  1. The current README.md with a table sorted highest to lowest in terms by RPS.
  2. A histogram of RPS
  3. A histogram of Latency

**Comment by Dhanus3133** [comment]
@tusharmath kindly assign to me I would like to work

**Comment by alankritdabral** [comment]
@Dhanus3133 do you wanna work together on this? i would learn a lot by working with you

**Comment by Dhanus3133** [comment]
Hey @alankritdabral no. I am almost done with the CI. Just a few fixes, have to be done!

**Comment by tusharmath** [comment]
@Dhanus3133 Let me know if you need help. Would love to get this done ASAP :-)

**Comment by Dhanus3133** [comment]
> @Dhanus3133 Let me know if you need help. Would love to get this done ASAP :-) 

I have sent you an DM on discord
